name: e2e테스트
on:
  pull_request:
    branches:
      - 'dev'
  push:
    branches:
      - 'dev'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          test: npm test:e2e
          record: true
          config-file: cypress.config.ts
          browser: firefox
          headless: false
          working-directory: ./client/
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
